title: Jacob Hautaniemi # your name (or website title) here
logo: "/images/IMG_2022.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Math/Physics➗. STEM Ambassador🧪. QUT📘. 
  <br><br>
  Connect with me!
  <br><br>
  <a href="https://www.linkedin.com/in/jacob-hautaniemi-315a29191/">View My LinkedIn Profile</a>
  <a href="https://twitter.com/JacobHautaniemi">Follow me on Twitter</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-181080013-1 # your Google Analytics tracking ID here
